# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rubenlucena.me" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Rubén Lucena
  avatar: avatar.png
  gravatar: "ruben.lucena@icloud.com"
  description: "Programación, gadgets, libros y juegos" # used by search engines
  
  # Header and footer text
  header_text: >
     <p>Programación, gadgets, libros y juegos</p>     
     
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>
  
  # Icons
  rss: false
  email_address: # full email address, e.g. "sam@example.com"
  behance:
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  github: "rubenlucena"
  google_plus: 
  instagram: 
  linkedin:  # full URL
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  steam: 
  tumblr: 
  twitter: "rubenlr_"
  wordpress: 
  youtube: 
  
  # Scripts
  google_analytics: # tracking id, e.g. "UA-000000-01"
  disqus_shortname:
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"
  
  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed